mysite/admin/urls.py
from flask import Blueprint
from mysite import app
from .views import *
admin = Blueprint('admin',__name__)

admin.add_url_rule('/',view_func=home,methods=['GET','POST'])
admin.add_url_rule('/login/',view_func=adminlogin,methods=['GET','POST'])
admin.add_url_rule('/logout/',view_func=admin_logout,methods=['GET'])
admin.add_url_rule('/showrow/<table>/',view_func=adminrow,methods=['GET','POST'])
admin.add_url_rule('/<table>/<int:id>/',view_func=admin_delete,methods=['GET','POST'])
admin.add_url_rule('/add/<t>/',view_func=admin_data_add)

mysite/api/urls.py
from mysite import app
from flask import Blueprint
from .views import *
api = Blueprint('api',__name__)


api.add_url_rule('/',view_func=api_docs,methods=['GET'])
api.add_url_rule('/users/',view_func=all_user,methods=['GET'])
api.add_url_rule('/user/<id>/',view_func=single_user,methods=['GET','POST'])
api.add_url_rule('/post',view_func=all_post)

mysite/blog/models.py
from mysite import db
#from mysite.home.models import User
from datetime import datetime

class Blog(db.Model):
  id = db.Column(db.Integer,primary_key=True)
  title = db.Column(db.String(100),unique=False,nullable=False)
  slug = db.Column(db.String(20),unique=False,nullable=False)
  body = db.Column(db.String(1000),unique=False,nullable=False)
  post_created = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
  post_image = db.Column(db.String(50),unique=False,nullable=True)
  views = db.Column(db.Integer,nullable=True,default=0)
  user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)
  like =  db.relationship('Like',backref='blog',lazy=True,passive_deletes=True)
    
class Like(db.Model):
  id = db.Column(db.Integer,primary_key=True)
  user_id = db.Column(db.Integer,db.ForeignKey('user.id',ondelete="CASCADE"),nullable=False)
  post_id = db.Column(db.Integer,db.ForeignKey('blog.id',ondelete="CASCADE"),nullable=False)

mysite/blog/forms.py
from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from wtforms import StringField, SubmitField

class PostForm(FlaskForm):
    title = StringField('Title')
    body = CKEditorField('Body')
    submit = SubmitField('Publish')

mysite/home/forms.py
from wtforms import Form,StringField,IntegerField,PasswordField , validators
from wtforms.validators import EqualTo,DataRequired,Email,Length
from flask_wtf import FlaskForm
class RegisterForm(FlaskForm):
  firstname = StringField('First Name',validators=[DataRequired(),Length(min=3)])
  lastname = StringField('Last Name',validators=[DataRequired(),Length(min=3)])
  email = StringField('Email',validators=[DataRequired(),Email(message=('That\'s not a valid email address.')),Length(min=6)])
  password = PasswordField('Password',validators=[DataRequired(),Length(min=6)])

class LoginForm(FlaskForm):
  email = StringField('Email',validators=[DataRequired(),Email(message=('That\'s not a valid email address.')),Length(min=6)])
  password = PasswordField('Password',validators=[DataRequired(),Length(min=6)])
  
class EmailVerificationForm(FlaskForm):
  code = StringField('Email Verification',validators=[DataRequired()])

mysite/admin/views.py
from flask import render_template,request,redirect,url_for,flash
from flask_login import login_required,logout_user,login_user,current_user
from mysite.home.models import User
from mysite.blog.models import Blog
from mysite import bcrypt,db
from sqlalchemy import text

# admin login
def adminlogin():
  if request.method == "POST":
    email = request.form["email"]
    password = request.form["password"]
    print(email,password)
    u = User.query.filter_by(email=email).first()
    if u:
      hashpass = bcrypt.check_password_hash(u.password,password)
      print(hashpass)
      if u.email == email and hashpass == True and u.is_admin == True:
        print("login admin")
        login_user(u,remember=True)
        print("admin success")
        return redirect(url_for("admin.home"))
      else:
        flash("envalid email or password")
        return redirect(url_for('admin.adminlogin',next='/admin/login'))
    else:
      flash("envalid email or password")
      return redirect(url_for('admin.adminlogin',next='/admin/login'))
  return render_template("admin/adminlogin.html")

#admin_logout
@login_required
def admin_logout():
  logout_user()
  return redirect(url_for('admin.adminlogin',next='/admin/login/'))

#adminhome
@login_required
def home():
  if current_user.is_admin == True:
    table_names = []
    for t in db.engine.table_names():
      capable = t.capitalize()
      table_names.append(capable)
    url = request
    print(url)
    return render_template("admin/adminhome.html",table = table_names,url=url)
  elif current_user.is_admin == False:
    print("hhh")
    return render_template("admin/adminlogin.html")
  return render_template("admin/adminhome.html")

# admin data table show
@login_required
def adminrow(table):
  if current_user.is_admin == True:
    url = request
    # select table related data
    sql = text(f'select * from {table}')
    result = db.engine.execute(sql)
    
    d = []
    for i in result:
      d.append(i)
    
    # select table columns
    u = []
    t = table
    #print(type(t))
    print(type(User))
    sqll = text(f"PRAGMA table_info({table});")
    user = db.engine.execute(sqll)
    for i in user:
      a = i[1]
      u.append(a)
    
    return render_template("admin/adminrow.html",d=d,u=u,t=t,url=url)
  elif current_user.is_admin == False:
    return render_template("admin/adminlogin.html")
  return render_template("admin/adminrow.html")

# admin data delete
@login_required
def admin_delete(table,id):
  if current_user.is_admin == True:
    print(request.path)
    sql = text(f"DELETE FROM {table} WHERE id={id}")
    db.engine.execute(sql)
    return redirect(url_for("admin.adminrow",table=table))
  elif current_user.is_admin == False:
    return redirect(url_for('admin.adminlogin',next='/admin/login'))
    render_template("admin/adminlogin.html")
  return redirect(url_for('admin.home'))

@login_required
def admin_data_add(t):
  if current_user.is_admin == True:
    return render_template("admin/adminadd.html")
  elif current_user.is_admin == False:
    return render_template("admin/adminlogin.html")
  return render_template("admin/adminadd.html")

mysite/api/views.py
from flask import Blueprint,jsonify
from mysite.home.models import User
from mysite.blog.models import Blog
from .serializer import blog_schema,blogs_schema
#api = Blueprint('api',__name__)


def api_docs():
  return jsonify({"api": "documentaion"})


def all_user():
  users = User.query.all()
  print(users)
  data = []
  for user in users:
    users_data = {}
    users_data['id'] = user.id
    users_data['firstname'] = user.firstname
    users_data['lastname'] = user.lastname
    users_data['email'] = user.email
    users_data['password'] = user.password
    users_data['is_admin'] = user.is_admin
    users_data['fallowing'] = len(user.fallowing)
    users_data['like'] = len(user.likes)
    users_data['posts'] = len(user.posts)
    data.append(users_data)
  print(data)
  return jsonify(data)



def single_user(id):
  users = User.query.all()
  alldata = []
  for user in users:
    data = dict(id = user.id,firstname=user.firstname,lastname=user.lastname,email=user.email,image_file=user.image_file)
    alldata.append(data)
  print(alldata[int(id)])
  return jsonify(alldata[int(id)])
  

# create serializer class
def all_post():
  post = Blog.query.all()
  print(post)
  data = blogs_schema.dump(post)
  print(data)
  return jsonify(data)

mysite/blog/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,jsonify
from flask_login import login_required,current_user
from mysite import db
from .models import Blog,Like
from mysite.home.models import User,Fallow
from .forms import PostForm

blog = Blueprint('blog',__name__)

@blog.route('/',methods=["GET","POST"])
@login_required
def index():
  if request.method == "POST":
    
    form = PostForm()
    if form.validate_on_submit():
      title = form.title.data
      body = form.body.data
      # title convert into slug
      data = title.split()
      tuple(data)
      slug = "-".join(data)
      blog = Blog(title=form.title.data,slug=slug,body=form.body.data,user_id=current_user.id)
      db.session.add(blog)
      db.session.commit()
      flash("write post")
  else:
    form = PostForm()
  return render_template('blog/index.html',form=form)

# read detail post
@blog.route('/read/<string:slug>/',methods=["GET","POST"])
@login_required
def read_post(slug):
  posts = Blog.query.filter_by(slug=slug).first()
  posts.views = posts.views + 1
  db.session.add(posts)
  db.session.commit()
  data = current_user.id in map(lambda x: x.user_id,posts.like)
  
  return render_template("blog/readpost.html",posts=posts,user=current_user.id,like=data)

#edit posts
@blog.route('/edit/<int:id>/')
def edit_post(id):
  print(id)
  post = Blog.query.filter_by(id=id).first()
  print(post)
  data = {}
  data['id'] = post.id
  data['title'] = post.title
  data['slug'] = post.slug
  data['like'] = len(post.like)
  
  #data['body'] = post.body
  data['post_created'] = post.post_created
  return jsonify({'post': data})


# like handel 
@blog.route('/like/<string:post_id>/',methods=['POST','GET'])
@login_required
def post_like(post_id):
  posts = Blog.query.filter_by(id=post_id).first()
  print(request.url)
  like = Like.query.filter_by(user_id=current_user.id,post_id=post_id).first()
  if like:
    db.session.delete(like)
    db.session.commit()
    
  else:
    like = Like(user_id=current_user.id,post_id = post_id)
    db.session.add(like)
    db.session.commit()
  
  return jsonify({'like': len(posts.like),'liked': current_user.id in map(lambda x: x.user_id,posts.like)})

# follow user
@blog.route('/fallow/<user_id>/',methods=['GET','POST'])
@login_required
def fallow_user(user_id):
  print(request.url)
  user = User.query.filter_by(id=user_id).first()
  print(len(user.fallowing))
  data = []
  for fallow in user.fallowing:
    data.append(fallow.id)
  if current_user.id in data:
    fallower = Fallow.query.filter_by(id=current_user.id).first()#
    user.fallowing.remove(fallower)
    db.session.commit()
    
  else:
  # get post related user id
   fallower = Fallow.query.filter_by(id=current_user.id).first()#
   user.fallowing.append(fallower)
   db.session.add(user)
   db.session.commit()
  return jsonify({'fallower': len(user.fallowing),'fallowed': True})

mysite/home/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,session,jsonify
import sqlalchemy
from .forms import RegisterForm,LoginForm,EmailVerificationForm
from .models import User,Fallow
from mysite.blog.models import Blog
from mysite import bcrypt,db,mail,final,socketio
from flask_login import login_user,current_user,login_required,logout_user
from .utils import email_verification,reset_pass_mail
import json
import jwt
from os import environ
from flask_socketio import send
import datetime
home = Blueprint('home',__name__)

@home.route('/')
def index():
  post = Blog.query.all()
  for i in post:
    print(i.users.image_file)
  popularPost = Blog.query.filter(Blog.views>2).all()
  return render_template("home/index.html",posts=post,popularPost=popularPost)
# register form 
@home.route('/register/',methods=['GET','POST'])
def user_register():
  if current_user.is_authenticated and current_user.is_active == True:
    return redirect(url_for("user.index"))
  if request.method == "POST":
    form = RegisterForm()
    if form.validate_on_submit():
      print(form.firstname.data,form.lastname.data,form.email.data,form.password.data)
      user = User.query.filter_by(email=form.email.data).first()
      if user:
        flash("Email Account Already Exist","danger")
        return redirect(url_for("home.user_login"))
      else:
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        new_user = User(firstname=form.firstname.data,lastname= form.lastname.data,email=form.email.data,password=pass_hash,is_active=False)
        new_fallow = Fallow()
        db.session.add(new_fallow)
        db.session.add(new_user)
        db.session.commit()
        token = jwt.encode({"email": new_user.email,"exp": datetime.datetime.utcnow()+datetime.timedelta(seconds=120)},environ['SECRET_KEY'],algorithm='HS256')
        url = f"{url_for('home.email_verify',token=token,_external=True)}"
        email_verification(url,form.email.data)
        flash("Please activet your check your email  ")
        return redirect("/login")
  else:
    form = RegisterForm()
  return render_template('home/signup.html',form=form)


# login form 
@home.route('/login/',methods=["GET","POST"])
def user_login():
  if current_user.is_authenticated and current_user.is_active == True:
    return redirect(url_for("user.index"))
  if request.method == "POST":
    form = LoginForm()
    if form.validate_on_submit():
      user = User.query.filter_by(email=form.email.data).first()
      
      if user and bcrypt.check_password_hash(user.password,form.password.data) and user. is_active == True:
        login_user(user,remember=True)
        return redirect(url_for("home.index"))
      else:
        flash("email or password dose not match ","danger")
        return redirect(url_for("home.user_login"))
  else:
    form = LoginForm()
  return render_template('home/login.html',form=form)
# logout user
@home.route('/logout/',methods=["GET","POST"])
def logout():
  logout_user()
  return redirect(url_for("home.user_login"))


# email_verification
@home.route('/email_verification/<token>/',methods=["GET","POST"])
def email_verify(token):
  print(token)
  try:
    token = jwt.decode(token,environ['SECRET_KEY'],algorithms='HS256')
    user = User.query.filter_by(email=token['email']).first()
    user.is_active = True
    db.session.add(user)
    db.session.commit()
  except jwt.ExpiredSignatureError:
    flash("token expired")
    return redirect("/register")
  except jwt.InvalidSignatureError:
    flash('envalid url')
    return redirect("/register")
  return redirect("/login")

@home.route('/forgotpassword/',methods=["GET","POST"])
def forget_password():
  if request.method == "POST":
    email = request.form.get("email")
    u = User.query.filter_by(email=email).first()

    if u:
      flash("Please check your email to reset your password ")
      token = jwt.encode({"email": u.email ,"exp": datetime.datetime.utcnow()+datetime.timedelta(seconds=60)},environ['SECRET_KEY'],algorithm="HS256")
      URL = f"{url_for('home.new_password',token=token,_external=True)}"
      reset_pass_mail(URL,u.email)
      with open("url.txt","w") as f:
        f.write(URL)
      return redirect('/forgotpassword/')
    else:
      flash("email accont not found")
      return redirect("/forgotpassword")
  return render_template("home/forgotpassword.html")


@home.route('/newpassword/<token>/',methods=["GET","POST"])
def new_password(token):
  try:
    u = jwt.decode(token, environ['SECRET_KEY'],algorithms="HS256")
    
    if request.method == "POST":
      email = User.query.filter_by(email=u['email']).first()
      pass_hash = bcrypt.generate_password_hash(request.form.get("pass"))
      email.password = pass_hash
      db.session.add(email)
      db.session.commit()
      flash("your password has been reset")
      return redirect(url_for('home.user_login'))
  except jwt.ExpiredSignatureError:
    flash("token expired")
    return redirect("/forgotpassword")
  except jwt.InvalidSignatureError:
    flash('envalid url')
    return redirect("/forgotpassword")
    #print(request.form.get("pass"))
  return render_template("home/newpassword.html")

mysite/user/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,jsonify
from flask_login import current_user,login_required
from mysite import db
from werkzeug.utils import secure_filename
import os
from .utils import save_image
from mysite.home.models import User
user = Blueprint('user',__name__)

@user.route('/')
@login_required
def index():
  views = 0
  for post in current_user.posts:
    views = views + post.views
  like = 0
  for post in current_user.posts:
    like = like+ len(post.like)
  print(like)
  return render_template("user/index.html",user=current_user,views=views,like=like)

@user.get('/userdata/')
@login_required
def userdata():
  views = 0
  for post in current_user.posts:
    views = views + post.views
  like = 0
  for post in current_user.posts:
    like = like+ len(post.like)
  return jsonify({'views': views})
#profile

@user.route('/profile/',methods=["GET","POST"])
@login_required
def user_profile():

  return render_template("user/profile.html")

@user.route('/profile-pic/',methods=['POST'])
@login_required
def profile_upload():
  f = request.files['picture']
  u = User.query.filter_by(id = current_user.id).first()
  save_im = save_image(f)
  print(save_im)
  u.image_file = save_im
  db.session.add(u)
  db.session.commit()
  
  return redirect(url_for("user.user_profile"))

mysite/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{{ url_for('static',filename='style.css' )}}" type="text/css" media="all" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block content %}{% endblock %}
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
  <div class="p-fix-b-0 bg-slate-100 p-x-6 shadoww b-ra-2">
    <p class="text-white mb-0 ">
      {{ message }}
    </p>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  
  {% block script %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/e916a9c960.js" crossorigin="anonymous"></script>

</body>
</html>

mysite/templates/headers.html
<header class="py-3 mb-3 border-bottom pf-t-0 bg-slate-200 z-ip">
  <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
    <a class="align-items-center text-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="" aria-controls="offcanvasExample">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
      </svg>
    </a>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">OkEarn</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body" >
        <ul class="nav flex-column align-items-left fw-bold ">
          <li class="nav-item text text-orange-50">

            <a {% if request.path=='/' %}class="nav-link text-orange-50 active"
              {% else %}
              class="nav-link text-orange-50"
              {% endif %}aria-current="page" href="/">            <i class="bi bi-house"></i>   Home</a>
          </li>
          <li class="nav-item">

            <a  {% if request.path=='/post' %}class="text-orange-50  active"
              {% else %}
              class="nav-link text-orange-50"
              {% endif %} href="#"><i class="bi bi-pencil-square"></i>  Post</a>
          </li>
          <li class="nav-item">

            <a class="nav-link " href="#"><i class="bi bi-chat-right-text"></i>  Comment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link ">
              <i class="bi bi-bar-chart"></i>  Status</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="#"><i class="bi bi-cash-stack"></i>   Earn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#"><i class="bi bi-badge-ad"></i>  Advertising</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="d-flex align-items-center">
      <form class="w-100 me-3">
        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
      </form>

      <div class="flex-shrink-0 dropdown">
        <a href="#" class="d-block link-dark text-decoration-none " id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="true">
          <img src="/static/media/profile_pic/{{ current_user.image_file }}" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
          <li><a
            {% if request.path=='/blog/' %}
            class="dropdown-item active"
            {% else %}
            class="dropdown-item"
            {% endif %}
            href="{{ url_for('blog.index')}}"><i class="bi bi-plus-square"></i>   New Post...</a></li>
          <li><a           {% if request.path=='/user/' %}
            class="dropdown-item active"
            {% else %}
            class="dropdown-item "
            {% endif %} href="{{ url_for('user.index' )}}"><i class="bi bi-bar-chart"></i> Post Statics</a></li>
          <li><a           {% if request.path=='/setting/' %}
            class="dropdown-item active"
            {% else %}
            class="dropdown-item"
            {% endif %}href="#"><i class="bi bi-gear"></i>  Settings</a></li>
          <li><a           {% if request.path=='/user/profile/' %}
            class="dropdown-item active"
            {% else %}
            class="dropdown-item"
            {% endif %}href="{{ url_for('user.user_profile' )}}"><i class="bi bi-person"></i>    Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a           {% if request.path=='/logout/' %}
            class="dropdown-item active"
            {% else %}
            class="dropdown-item "
            {% endif %} href="{{ url_for('home.logout') }}"><i class="bi bi-box-arrow-right"></i>  Sign out</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

mysite/templates/home.html
<div class="roww border shadoww flex">
  <div class="coll-10 flex t-center">
      <button class="btnn"onclick="getData()">Get Dat</button>
  <script src="{{ url_for('static', filename='js/home.js') }}" type="text/javascript" charset="utf-8"></script>
  </div>
</div>

mysite/templates/withoutloginheader.html
<nav class="bg-slate-100 flex space-bet t-center shadoww pf-t-0">
  <div class="flex nav-left p-left-20">
    <p id="menu" class="d-display-none m-display-block f-size-10 m-b-0">
      <i class="bi bi-list"></i>
    </p>
    <ul id="ul" class="flex list-style-none p-left m-colum text-left m-nav m-b-0 m-auto">
      <h2 class="d-display-none m-display-block">OKEARN</h2>
      <li class="m-p-top-20 m-left-4"><a class="text-decorations-none p-x-6 text-orange-50 m-left-4" href="/"><i class="fas fa-home"></i>  Home</a></li>
      <li class="m-p-top-20 m-left-4"><a
        {% if request.path=='/blog/' %}class="text-decorations-none p-x-6 m-left-4 "
        {% else %}
        class="text-decorations-none p-x-6 text-orange-50 m-left-4 active"
        {% endif %}
        href="{{ url_for('home.user_login') }}"><i class="fas fa-sign-in-alt"></i>     Login</a></li>
      <li class="m-p-top-20 m-left-4"><a class="text-decorations-none p-x-6 text-orange-50 m-left-4" href="{{ url_for('home.user_register') }}">  <i class="fas fa-user-plus"></i>  Register</a></li>
    </ul>

  </div>
  <div class="nav-right p-right-20 flex t-center">
    <h2 class="m-b-0">OKERAN</h2>
  </div>

</nav>
<script src="{{ url_for('static',filename='js/nav.js')}}"></script>